package Lab7;

public class PolicyException extends Exception {
    public int ID;

    public PolicyException(int ID) {
        super();
        this.ID = ID;
    }

    public String toString() {
        return String.format("The Policy ID was not valid and a New ID (%d) is generated by admin and assigned for the Policy", ID);
    }
}
