package Lab5;

public class PolicyException extends Exception {
    private int ID;

    public PolicyException() {

    }

    public int generateID() {
        return 3000000 + (int) (Math.random() * 1000000);
    }


    public String toString() {
        return String.format("The Policy ID was not valid and a New ID (%d) is generated by admin and assigned for the Policy", ID);
    }
}
